# Generated by Django 3.0.5 on 2021-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_detail',
            name='walletid',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_detail',
            name='walletid',
            field=models.IntegerField(max_length=100),
        ),
    ]
