# Generated by Django 3.0.5 on 2021-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_api', '0003_auto_20210115_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_monthly_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('walletid', models.IntegerField(max_length=100)),
                ('amount_add', models.IntegerField(default=0, max_length=100)),
                ('amount_debit', models.IntegerField(default=0, max_length=100)),
            ],
        ),
    ]
